"""Initial YATRA360 database schema

Revision ID: 9e44daceb0a8
Revises: 
Create Date: 2026-09-05 19:18:30.447327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e44daceb0a8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destinations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('entry_fee', sa.Float(), nullable=False),
    sa.Column('safety_rating', sa.Float(), nullable=False),
    sa.Column('is_hidden_gem', sa.Boolean(), nullable=False),
    sa.Column('base_crowd_level', sa.String(length=20), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('accessibility_info', sa.Text(), nullable=True),
    sa.Column('estimated_visit_duration', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('entry_fee >= 0.0', name='chk_dest_entry_fee'),
    sa.CheckConstraint('safety_rating >= 1.0 AND safety_rating <= 5.0', name='chk_dest_safety_rating'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_destinations_category'), 'destinations', ['category'], unique=False)
    op.create_index('ix_destinations_category_state', 'destinations', ['category', 'state'], unique=False)
    op.create_index(op.f('ix_destinations_city'), 'destinations', ['city'], unique=False)
    op.create_index(op.f('ix_destinations_is_hidden_gem'), 'destinations', ['is_hidden_gem'], unique=False)
    op.create_index(op.f('ix_destinations_name'), 'destinations', ['name'], unique=False)
    op.create_index(op.f('ix_destinations_slug'), 'destinations', ['slug'], unique=True)
    op.create_index(op.f('ix_destinations_state'), 'destinations', ['state'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('tourist', 'business', 'admin')", name='chk_user_role'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('contact_info', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businesses_category'), 'businesses', ['category'], unique=False)
    op.create_index('ix_businesses_category_city', 'businesses', ['category', 'city'], unique=False)
    op.create_index(op.f('ix_businesses_city'), 'businesses', ['city'], unique=False)
    op.create_index(op.f('ix_businesses_name'), 'businesses', ['name'], unique=False)
    op.create_index(op.f('ix_businesses_owner_id'), 'businesses', ['owner_id'], unique=False)
    op.create_index(op.f('ix_businesses_state'), 'businesses', ['state'], unique=False)
    op.create_table('crowd_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('crowd_level', sa.String(length=20), nullable=False),
    sa.Column('visitor_count', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('visitor_count IS NULL OR visitor_count >= 0', name='chk_crowd_visitor_count'),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crowd_metrics_crowd_level'), 'crowd_metrics', ['crowd_level'], unique=False)
    op.create_index('ix_crowd_metrics_dest_recorded', 'crowd_metrics', ['destination_id', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_crowd_metrics_destination_id'), 'crowd_metrics', ['destination_id'], unique=False)
    op.create_index(op.f('ix_crowd_metrics_recorded_at'), 'crowd_metrics', ['recorded_at'], unique=False)
    op.create_table('itineraries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('budget IS NULL OR budget >= 0.0', name='chk_itinerary_budget'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itineraries_user_id'), 'itineraries', ['user_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('reported_crowd_level', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='chk_review_rating'),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reviews_dest_created', 'reviews', ['destination_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_reviews_destination_id'), 'reviews', ['destination_id'], unique=False)
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.create_table('safety',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('safety_level', sa.String(length=50), nullable=False),
    sa.Column('safety_rating', sa.Float(), nullable=True),
    sa.Column('risk_description', sa.Text(), nullable=True),
    sa.Column('emergency_information', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=150), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('safety_rating IS NULL OR (safety_rating >= 1.0 AND safety_rating <= 5.0)', name='chk_safety_rating'),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_safety_dest_updated', 'safety', ['destination_id', 'updated_at'], unique=False)
    op.create_index(op.f('ix_safety_destination_id'), 'safety', ['destination_id'], unique=False)
    op.create_table('itinerary_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('itinerary_id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('visit_order', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('day_number >= 1', name='chk_itinerary_item_day'),
    sa.CheckConstraint('visit_order >= 1', name='chk_itinerary_item_order'),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('itinerary_id', 'day_number', 'visit_order', name='uq_itinerary_day_order')
    )
    op.create_index(op.f('ix_itinerary_items_destination_id'), 'itinerary_items', ['destination_id'], unique=False)
    op.create_index(op.f('ix_itinerary_items_itinerary_id'), 'itinerary_items', ['itinerary_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_itinerary_items_itinerary_id'), table_name='itinerary_items')
    op.drop_index(op.f('ix_itinerary_items_destination_id'), table_name='itinerary_items')
    op.drop_table('itinerary_items')
    op.drop_index(op.f('ix_safety_destination_id'), table_name='safety')
    op.drop_index('ix_safety_dest_updated', table_name='safety')
    op.drop_table('safety')
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_destination_id'), table_name='reviews')
    op.drop_index('ix_reviews_dest_created', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_itineraries_user_id'), table_name='itineraries')
    op.drop_table('itineraries')
    op.drop_index(op.f('ix_crowd_metrics_recorded_at'), table_name='crowd_metrics')
    op.drop_index(op.f('ix_crowd_metrics_destination_id'), table_name='crowd_metrics')
    op.drop_index('ix_crowd_metrics_dest_recorded', table_name='crowd_metrics')
    op.drop_index(op.f('ix_crowd_metrics_crowd_level'), table_name='crowd_metrics')
    op.drop_table('crowd_metrics')
    op.drop_index(op.f('ix_businesses_state'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_owner_id'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_name'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_city'), table_name='businesses')
    op.drop_index('ix_businesses_category_city', table_name='businesses')
    op.drop_index(op.f('ix_businesses_category'), table_name='businesses')
    op.drop_table('businesses')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_destinations_state'), table_name='destinations')
    op.drop_index(op.f('ix_destinations_slug'), table_name='destinations')
    op.drop_index(op.f('ix_destinations_name'), table_name='destinations')
    op.drop_index(op.f('ix_destinations_is_hidden_gem'), table_name='destinations')
    op.drop_index(op.f('ix_destinations_city'), table_name='destinations')
    op.drop_index('ix_destinations_category_state', table_name='destinations')
    op.drop_index(op.f('ix_destinations_category'), table_name='destinations')
    op.drop_table('destinations')
    # ### end Alembic commands ###
